export const EMPLOYEE_Types = {
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  SHOW_CREATE_EMPLOYEE_FROM: 'SHOW_CREATE_EMPLOYEE_FROM',
  CREATE_EMPLOYEE_MODAL_OPEN: 'CREATE_EMPLOYEE_MODAL_OPEN',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE'
}
