export const MENU_Types = {
  GET_MENU_ITEMS: 'GET_MENU_ITEMS',
  GET_MENU_ITEMS_SUCCESS: 'GET_MENU_ITEMS_SUCCESS',
  GET_ITEM_DETAILS: 'GET_ITEM_DETAILS',
  GET_ITEM_DETAILS_SUCCESS: 'GET_ITEM_DETAILS_SUCCESS',
  SET_UI_VALUES: 'SET_UI_VALUES',
  CREATE_MENU: 'CREATE_MENU'
  // ADD_MENU_MODAL_OPEN: 'ADD_MENU_MODAL_OPEN',

}
