export const Types = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  GET_ROLES: 'ROLES',
  GET_ROLES_SUCCESS: 'ROLES_SUCCESS',
  LOG_OUT: 'LOG_OUT'
}
